[{"name": "test.test_suicide_weather.SuicideWeather.test_calls", "status": "errored", "message": "No tables found", "passed": false, "points": ["p05-07.1"], "backtrace": ["  File \"/Users/juhassio/anaconda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/juhassio/anaconda/lib/python3.6/unittest/case.py\", line 597, in run\n    self.setUp()\n", "  File \"/Users/juhassio/Desktop/hy-data-analysis-with-python-summer-2019/part05-e07_suicide_weather/test/test_suicide_weather.py\", line 26, in setUp\n    self.tup = suicide_weather()\n", "  File \"/Users/juhassio/Desktop/hy-data-analysis-with-python-summer-2019/part05-e07_suicide_weather/src/suicide_weather.py\", line 15, in suicide_weather\n    weather_df = pd.read_html('src/file.html')\n", "  File \"/Users/juhassio/anaconda/lib/python3.6/site-packages/pandas/io/html.py\", line 906, in read_html\n    keep_default_na=keep_default_na)\n", "  File \"/Users/juhassio/anaconda/lib/python3.6/site-packages/pandas/io/html.py\", line 743, in _parse\n    raise_with_traceback(retained)\n", "  File \"/Users/juhassio/anaconda/lib/python3.6/site-packages/pandas/compat/__init__.py\", line 344, in raise_with_traceback\n    raise exc.with_traceback(traceback)\n"]}, {"name": "test.test_suicide_weather.SuicideWeather.test_return_value", "status": "errored", "message": "No tables found", "passed": false, "points": ["p05-07.1"], "backtrace": ["  File \"/Users/juhassio/anaconda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/juhassio/anaconda/lib/python3.6/unittest/case.py\", line 597, in run\n    self.setUp()\n", "  File \"/Users/juhassio/Desktop/hy-data-analysis-with-python-summer-2019/part05-e07_suicide_weather/test/test_suicide_weather.py\", line 26, in setUp\n    self.tup = suicide_weather()\n", "  File \"/Users/juhassio/Desktop/hy-data-analysis-with-python-summer-2019/part05-e07_suicide_weather/src/suicide_weather.py\", line 15, in suicide_weather\n    weather_df = pd.read_html('src/file.html')\n", "  File \"/Users/juhassio/anaconda/lib/python3.6/site-packages/pandas/io/html.py\", line 906, in read_html\n    keep_default_na=keep_default_na)\n", "  File \"/Users/juhassio/anaconda/lib/python3.6/site-packages/pandas/io/html.py\", line 743, in _parse\n    raise_with_traceback(retained)\n", "  File \"/Users/juhassio/anaconda/lib/python3.6/site-packages/pandas/compat/__init__.py\", line 344, in raise_with_traceback\n    raise exc.with_traceback(traceback)\n"]}]